# Main 데이터베이스 설정
main:
  # 데이터 소스 설정 (데이터베이스 연결을 관리하는 HikariCP 관련 설정 포함)
  datasource:
    single:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/sample?serverTimezone=UTC&characterEncoding=UTF-8
      read-only: false
      username: sample
      password: ENC(Mc7GDTyzk57XXU7hf+OTYl8n20zzViY8BIclFDIUN8vmuBGVNcRFVNOXlO3MONlH) # password1!
      poolName: mysqlDbConnectionPool
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      max-life-time: 300000
      connection-test-query: SELECT 1
  # JPA 설정
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        highlight-sql: true
        use-sql-comments: true

# Redis 설정
redis:
  cluster:
    nodes:
      127.0.0.1:7001
