# Main(PostgreSQL) Datasource
#main:
#  datasource:
#    single:
#      driver-class-name: org.postgresql.Driver
#      jdbc-url: jdbc:postgresql://127.0.0.1:5432/sample
#      read-only: false
#      username: sample
#      # password: password1!
#      password: ENC(Mc7GDTyzk57XXU7hf+OTYl8n20zzViY8BIclFDIUN8vmuBGVNcRFVNOXlO3MONlH)
#      poolName: postgresDbConnectionPool
#      maximum-pool-size: 5
#      minimum-idle: 5
#      idle-timeout: 10000
#      max-life-time: 580000
#      connection-test-query: SELECT 1
# Main(MySQL) Datasource
main:
  datasource:
    single:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sample?serverTimezone=UTC&characterEncoding=UTF-8
        read-only: false
        username: sample
        # password: password1!
        password: ENC(Mc7GDTyzk57XXU7hf+OTYl8n20zzViY8BIclFDIUN8vmuBGVNcRFVNOXlO3MONlH)
        poolName: mysqlDbConnectionPool
        maximum-pool-size: 5
        minimum-idle: 5
        idle-timeout: 10000
        max-life-time: 580000
        connection-test-query: SELECT 1
  # JPA 설정
  jpa:
    generate-ddl: false # 데이터베이스 테이블을 자동으로 생성
    show-sql: false # 콘솔에 실행되는 테이블 생성 DDL을 출력
    # PostgreSQL
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        highlight-sql: true
        use-sql-comments: true
        physical-naming-strategy: com.example.boilerplate.config.MainJpaNamingStrategy

# Redis 설정
redis:
  cluster:
    nodes:
