# SERVER 설정
server:
  port: 9092
  servlet:
    context-path: /api
  error:
    path: /error
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      max-days: 14
      pattern: '%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b'
      rotate: true
    basedir: .

---
# Config 설정
spring:
  application:
    # Config Server에서 참조하는 설정 파일의 애플리케이션 이름을 설정
    name: datasource
  config:
    # 외부 설정 파일 설정 - Config Server 정보를 설정
    import: "optional:configserver:http://localhost:9091/"
  cloud:
    config:
      # 활성화할 프로파일을 설정(local, dev, qa, prod)
      profile: cloud

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
# SPRING 설정
spring:
  web:
    locale: ko_KR #spring.mvc.locale is deprecated
    resources:
      add-mappings: false
  messages:
    basename: message/messages
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: cloud
    group:
      local: profiles-local
           , logging-type-console
           , logging-level-local
           , main_db_single
      dev: profiles-dev
         , logging-type-console
         , logging-level-dev
         , main_db_replication
      cloud: profiles-cloud
         , logging-type-console
         , logging-level-local
         , main_db_single

---
# LOCAL 설정
spring.config.activate.on-profile: "profiles-local"
spring:
  config:
    import:
      classpath:config/datasource/datasource-local.yml,
      classpath:config/environment/environment-local.yml


---
# DEV 설정
spring.config.activate.on-profile: "profiles-dev"
spring:
  config:
    import:
      classpath:config/datasource/datasource-dev.yml,
      classpath:config/environment/environment-dev.yml

---
# CLOUD 설정
spring.config.activate.on-profile: "profiles-cloud"
spring:
  config:
    import:
      classpath:config/environment/environment-local.yml
