# SERVER 설정
server:
  port: 9091
  servlet:
    context-path: /api
  error:
    path: /error
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      max-days: 14
      pattern: '%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b'
      rotate: true
    basedir: .

# SPRING 설정
spring:
  web:
    locale: ko_KR #spring.mvc.locale is deprecated
    resources:
      add-mappings: false
  messages:
    basename: message/messages
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
    group:
      local: profiles-local
        , logging-type-console , logging-level-local
        , main_db_single
      dev: profiles-dev
        , logging-type-console, logging-level-dev
        , main_db_replication
      stg: profiles-stg
        , logging-type-file-absolute, logging-level-stg
        , main_db_replication
      prd: profiles-prd
        , logging-type-file-absolute, logging-level-prd
        , main_db_replication

---
# LOCAL 설정
spring.config.activate.on-profile: "profiles-local"
spring:
  config:
    import:
      classpath:config/datasource/datasource-local.yml,
      classpath:config/environment/environment-local.yml

---
# DEV 설정
spring.config.activate.on-profile: "profiles-dev"
spring:
  config:
    import:
      classpath:config/datasource/datasource-dev.yml,
      classpath:config/environment/environment-dev.yml

---
# STG 설정
spring.config.activate.on-profile: "profiles-stg"
spring:
  config:
    import:
      classpath:config/datasource/datasource-stg.yml,
      classpath:config/environment/environment-stg.yml

---
# PRD 설정
spring.config.activate.on-profile: "profiles-prd"
spring:
  config:
    import:
      classpath:config/datasource/datasource-prd.yml,
      classpath:config/environment/environment-prd.yml
