# 암호화 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: gYnK0KZ/3UonUIRzdEHIWiy87fie0dZcIUrDH1KNK1zq24Dg2K18FftH/m1TCVoC

# JWT 설정
jwt:
  secret-key: 055b0be94bd8c5f8967a7cda82855770486892cb727d9c544055e4f83380bcda

# SpringDoc 설정
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    filter: true
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


